### ISSUE TITLE
Usage with VM

### ISSUE THREAD

**Issue by kingil** [rvojcik/rt-server-client#23]
Hello!

We are using Ubuntu on proxmox virtualization. And now we want to collect information from out infrastructure to racktables with auto-discovery.

When i started system-info, i got error:

`# system-info -d
[DEBUG] Opening config: /etc/rt-server-client/main.conf
[DEBUG] Database connection [host, port, passwd, database, user] = [ maria01, 3306, xxxxxx, racktables, racktables ]
[DEBUG] Initializing RT Api object
[DEBUG] Device list: ['eth0']
[DEBUG] Processing interface eth0
[DEBUG] IPv4: [['172.10.11.213']]
[DEBUG] IPv6: [[]]
[DEBUG] Connection: ['', '']
/bin/sh: 1: omreport: not found
/bin/sh: 1: ipmitool: not found
[DEBUG] Drac IP:
[DEBUG] Product name: Standard PC (i440FX + PIIX, 1996)
[DEBUG] Service Tag: Not
[DEBUG] Vendor: QEMU
Traceback (most recent call last):
  File "/usr/local/bin/system-info", line 142, in <module>
    server_object.DiscoverAll()
  File "/usr/local/lib/python3.6/dist-packages/rt_server_client/sysinfo/__init__.py", line 64, in DiscoverAll
    self.DiscoverSystem()
  File "/usr/local/lib/python3.6/dist-packages/rt_server_client/sysinfo/__init__.py", line 153, in DiscoverSystem
    elif vendor == 'QEMU':
NameError: name 'vendor' is not defined
`
What's wrong? There are not omreport and ipmi and can't be.

**Comment by rvojcik** [comment]
@kingil hi, sorry for delay. I somehow missed this issue
